---

- name: ensure mysql python packages are present
  apt:
    name: python-mysqldb

- name: create database
  mysql_db:
    name: '{{mediawiki_db.name}}'
    login_unix_socket: '/var/run/mysqld/mysqld.sock'

- name: create database user
  mysql_user:
    name: '{{mediawiki_db.user}}'
    password: '{{mediawiki_db.password}}'
    priv: '{{mediawiki_db.name}}.*:ALL'
